server.port=6099
spring.r2dbc.username=${db_username}
spring.r2dbc.password=${db_password}
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/bulk-transaction
#spring.flyway.url=jdbc:postgresql://localhost:5432/bulk-transaction
spring.flyway.user=${db_username}
spring.flyway.password=${db_password}
spring.flyway.enabled=false
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.schema-locations=classpath:transaction.sql

spring.r2dbc.properties.schema=public


# JWT configuration
jwt.secret=${secret_key}
jwt.validity-ms=3600000

#FOR INTEGRATION WITH EXTERNAL SERVICE

app.downstream.base-url= http://localhost:8081/api/v1/transaction-service
app.processing.concurrency=20
# ==========================
# === RESILIENCE4J RETRY ===
# ==========================

# Retry configuration for Transaction-Service
resilience4j.retry.instances.transactionServiceRetry.max-attempts=3
resilience4j.retry.instances.transactionServiceRetry.wait-duration=2s
resilience4j.retry.instances.transactionServiceRetry.exponential-backoff-multiplier=2
resilience4j.retry.instances.transactionServiceRetry.enable-exponential-backoff=true


# ====================================
# === RESILIENCE4J CIRCUIT BREAKER ===
# ====================================

# Circuit breaker configuration for Transaction-Service
resilience4j.circuitbreaker.instances.transactionServiceCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.transactionServiceCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.transactionServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.transactionServiceCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.transactionServiceCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true


# ==========================
# === MANAGEMENT / METRICS ===
# ==========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always




